version: '3'
services:
  php:
    image: php:8.1-fpm
    container_name: app-php
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - app-network

  nginx:
    environment:
      - NGINX_CONF_FILE=./nginx/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
